### ISSUE TITLE
Open Source GPS Debug

### ISSUE THREAD

**Issue by preciousmetalsirarollover** [pytroll/pytroll.github.io#17]
Do you guys have a tutorial for PyTroll?

**Comment by djhoese** [comment]
Under the "Tutorials, examples…" section on the pytroll website (http://pytroll.github.io/, the repository which you made this issue on :wink: ) there is a link to a slideshow going over the various tools in the Pytroll suite of packages. That section also links to our examples repository (https://nbviewer.jupyter.org/github/pytroll/pytroll-examples/tree/master/) which is just a special viewer on top of this github repository: https://github.com/pytroll/pytroll-examples/

Let me know if you have any additional questions.
