### ISSUE TITLE
troll?

### ISSUE THREAD

**Issue by zmoon** [pytroll/pytroll.github.io#33]
I am curious about the name. Is it a reference to something? In the logo it is "PyTROLL", making it look like the troll part is an acronym. What is the history (of the name)? I couldn't find anything about this here or in the *BAMS* paper.

**Comment by djhoese** [comment]
This is definitely a question for @mraspaud or @adybbroe. Sorry I can't be of more help.

**Comment by adybbroe** [comment]
@zmoon The open source collaboration that became Pytroll started in 2009 by a handful of developers at the Danish Met Service (DMI) and SMHI (@mraspaud and myself). We realized that we had a lot in common. We all liked Python and was solving and wanted to solve a lot of similar problems, among others getting rid of ill-suited proprietary SW in our satellite data production systems. At some point during 2010, I believe, it had grown big enough that we felt it needed a name. The *troll" in Pytroll should hint at the Nordic/Scandinavian heritage. Soon after colleagues at FMI (the Finnish Met Service) and the Icelandic Met Service joined. The name was not liked equally well by all of us, but it was the best we could come up with. Now we are stuck with it. :-)

**Comment by zmoon** [comment]
Thanks @adybbroe that is interesting. Could be nice to have some of that on Pytroll website somewhere?
