### ISSUE TITLE
pytroll overview page should list python2/python3 status

### ISSUE THREAD

**Issue by gerritholl** [pytroll/pytroll.github.io#5]
With the cliff edge of the end of Python2 looming ever closer upon a community where a lot of Python2-only code is still around, It would be very useful if the [pytroll packages overview](http://pytroll.github.io/pytroll_packages_overview.html) categorised the packages as:

- Python 2 only
- Both Python 2 and Python 3
- Python 3 only

**Comment by djhoese** [comment]
@gerritholl Thanks. Great idea. I'll speak for myself and say that I would like to have one overall section on this site specifically that says "All PyTroll packages will no longer support python 2 starting <season> of <year>". I'm not sure how the other devs feel about that.

We should add a message to all higher level packages' sphinx docs though.
